# ⃣1 Create & Reshape Magic
Task:
● Create an array from 1 to 12
● Convert it into a 3×4 matrix
● Print:
○ Shape
○ Number of elements
○ Data type
Hint:
Think about arange() and how reshape(rows, columns) works.


In [ ]:
import numpy as np

In [ ]:
arr1=np.arange(1,13)

In [ ]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr=arr1.reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.size

12

In [ ]:
arr.dtype

dtype('int64')

# 2]Even Number Finder
Task:
● Create numbers from 1 to 20.
● Print only even numbers.
● Print how many even numbers are there.
Hint:
Use a condition like number % 2 == 0 inside square brackets.

In [ ]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
arr1=arr[arr%2==0]
arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr1.size

10

# ⃣3Row Sum Challenge
Task:
● Create a 3×3 random integer matrix (values between 1–10).
● Print row sums.
● Print column sums.
● Print total sum.
Hint:
Look at the axis parameter. One axis works row-wise, the other column-wise

In [ ]:
arr=np.arange(1,10)
arr1=arr.reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.sum(arr1,axis=1)

array([ 6, 15, 24])

In [ ]:
np.sum(arr1,axis=0)

array([12, 15, 18])

In [ ]:
np.sum(arr1)

np.int64(45)

# ⃣4 Maximum Finder
Task:
● Create a 4×4 random matrix.
● Find the maximum value.
● Find its position (row, column).
Hint:
First find the index in flattened form, then convert it back to row and column

In [ ]:
arr=np.arange(1,17)
arr1=arr.reshape(4,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
max_value=np.max(arr1)
print('Maximum value:',max_value)

Maximum value: 16


In [ ]:
max_index=np.argmax(arr1)
max_position=np.unravel_index(max_index,arr1.shape)
print('Position of maximum value:',max_position)

Position of maximum value: (np.int64(3), np.int64(3))


#5]Replace Using Condition
Task:
● Create numbers from 1 to 15.
● Replace all numbers divisible by 3 with -1.
Hint:
Select elements using a condition and assign a new value directly.


In [ ]:
arr=np.arange(1,16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
arr[arr%3==0]=-1
arr

array([ 1,  2, -1,  4,  5, -1,  7,  8, -1, 10, 11, -1, 13, 14, -1])

# 6]Simple Matrix Operations
Task:
● Create two 3×3 random matrices.
● Add them.
● Multiply them element-wise.
● Multiply them using matrix multiplication

In [ ]:
arr=np.arange(1,10)
arr1=arr.reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr=np.arange(5,14)
arr2=arr.reshape(3,3)
arr2

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [ ]:
np.sum(arr1+arr2)

np.int64(126)

In [ ]:
element_wise=arr1*arr2
element_wise

array([[  5,  12,  21],
       [ 32,  45,  60],
       [ 77,  96, 117]])

In [ ]:
arr1.dot(arr2)

array([[ 54,  60,  66],
       [126, 141, 156],
       [198, 222, 246]])

# ⃣ 7Mini ML Style Question
Task:
Given:
X = np.array([[2, 3],
[4, 5],
[6, 7]])
Multiply each row by 10 without using loops.
Expected output:
[[20 30]
[40 50]
[60 70]]
Hint:
When multiplying an array by a number, NumPy automatically applies it to every element

In [ ]:
X = np.array([[2, 3], [4, 5], [6, 7]])

result = X * 10

print(result)

[[20 30]
 [40 50]
 [60 70]]


8️⃣Filter Rows Based on Condition
Task:
● Create a 5×3 random matrix (values between 0–20).
● Print only rows where row sum > 30.

In [ ]:
X = np.random.randint(0, 21, (5, 3))

print(X)

print(X[X.sum(axis=1) > 30])

[[ 9 18  4]
 [ 7 18  0]
 [20  6 12]
 [ 6  5  7]
 [20  2  0]]
[[ 9 18  4]
 [20  6 12]]


9️⃣Reverse an Array
Task:
● Create numbers from 1 to 10.
● Reverse the array using slicing.

In [ ]:
arr = np.arange(1, 11)

print(arr[::-1])

[10  9  8  7  6  5  4  3  2  1]


🔟 Simple Normalization
Task:
● Create a 3×3 random matrix.
● Divide each row by its row sum.

In [ ]:
X = np.random.rand(3, 3)

result = X / X.sum(axis=1, keepdims=True)

print(result)

[[0.3604599  0.18654813 0.45299197]
 [0.28303955 0.50659779 0.21036266]
 [0.28680637 0.55473789 0.15845574]]


Bonus (Optional)


1. Swap first and last column of a matrix.

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

A[:, [0, -1]] = A[:, [-1, 0]]

print(A)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


2. Create a 4×4 identity matrix.

In [ ]:
np. ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

3. Create a 5×5 matrix filled with zeros except the border filled with 1.

In [ ]:
A = np.zeros((5, 5), dtype=int)

A[0, :] = 1
A[-1, :] = 1
A[:, 0] = 1
A[:, -1] = 1

print(A)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
